### ISSUE TITLE
Rearrange Background for desktop version.

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/statebox.github.io#8]
The "Very blockchain" thing is cut atm and the fancy laser floor is not displayed. The image should be rescaled/shifted upwards so that these nice details are visible.

**Comment by antonleviathan** [comment]
This is a bit problematic at the moment because the background stretches to "cover" the screen so on some screen sizes it will look borked. The plan is to create new graphics, which are similar to this (since we have to take this down anyways due to potential copyright infringement), and have the text and "central" elements separate from the background so the background can fill the screen and we can center and determine the size of the the text + graphics in the middle. This will also allow us to animate stuff etc.

Going to close this for now because we can't really do much until we get these graphics.

**Comment by FabrizioRomanoGenovese** [comment]
Can't we just ask the guy that built the meme generator if we can use it for our logo? :D

**Comment by antonleviathan** [comment]
We could definitely try... but @wires wanted to get some designer to do stuff for us anyways.

**Comment by FabrizioRomanoGenovese** [comment]
Sure. But I'm talking about a temporary fix, if possible. We will surely make it better in the future, but I think it's worth to have something presentable right now that quite a lot of big personalities from academia are visiting the Website.

**Comment by antonleviathan** [comment]
It looks strange with a black/purple background though. :(

**Comment by FabrizioRomanoGenovese** [comment]
Sure. But I'm talking about a temporary fix, if possible. We will surely make it better in the future, but I think it's worth to have something presentable right now that quite a lot of big personalities from academia are visiting the Website.
